//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string designType { get; set; }
        public string LastName { get; set; }
        public string Postcode { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Size { get; set; }
        public string ShirtStyle { get; set; }
        public string jeans { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Paymentmethod { get; set; }
    }
}
