//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JeansFit
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> Skinny { get; set; }
        public Nullable<bool> Slim { get; set; }
        public Nullable<bool> Straight { get; set; }
        public Nullable<bool> Relaxed { get; set; }
    }
}
