//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenSize
    {
        public int Id { get; set; }
        public string Shirt { get; set; }
        public string Collar { get; set; }
        public string Blazer { get; set; }
        public string Bottom { get; set; }
        public string Waist { get; set; }
        public string InsideLeg { get; set; }
        public string Shoe { get; set; }
        public Nullable<int> AccountId { get; set; }
    }
}
