//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutfitsDesign
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> Style1 { get; set; }
        public Nullable<bool> Style2 { get; set; }
        public Nullable<bool> Style3 { get; set; }
        public Nullable<bool> Style4 { get; set; }
        public Nullable<bool> Style5 { get; set; }
        public Nullable<bool> Style6 { get; set; }
        public Nullable<bool> Style7 { get; set; }
        public Nullable<bool> Style8 { get; set; }
        public Nullable<bool> Style9 { get; set; }
        public Nullable<bool> Style10 { get; set; }
        public Nullable<bool> Style11 { get; set; }
        public Nullable<bool> Style12 { get; set; }
        public Nullable<bool> Style13 { get; set; }
        public Nullable<bool> Style14 { get; set; }
        public Nullable<bool> Style15 { get; set; }
        public Nullable<bool> Style16 { get; set; }
    }
}
