//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Shirts { get; set; }
        public string TeesAndPolos { get; set; }
        public string JumpersAndSweatShirts { get; set; }
        public string TrouserAndJeans { get; set; }
        public string Shorts { get; set; }
        public string BlazersAndJackets { get; set; }
        public string Coats { get; set; }
        public string Shoes { get; set; }
    }
}
