//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryComponent
    {
        public int Id { get; set; }
        public Nullable<bool> TryNew { get; set; }
        public Nullable<bool> DiscoverNewTrend { get; set; }
        public Nullable<bool> SaveTime { get; set; }
        public Nullable<bool> ExpertAdvice { get; set; }
        public Nullable<bool> AccesstoExclusiveBrands { get; set; }
        public Nullable<int> AccountId { get; set; }
    }
}
