//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNVG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SNVGEntities : DbContext
    {
        public SNVGEntities()
            : base("name=SNVGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PrimaryComponent> PrimaryComponents { get; set; }
        public virtual DbSet<MenSize> MenSizes { get; set; }
        public virtual DbSet<ShirtStyle> ShirtStyles { get; set; }
        public virtual DbSet<JeansFit> JeansFits { get; set; }
        public virtual DbSet<OutfitsDesign> OutfitsDesigns { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
    }
}
